#!/usr/bin/env python3
"""
examples/python/14_tuntap_replay.py
───────────────────────────────────────
Demonstrates the native TUN/TAP packet injection sink.

This script runs `netpipe` to read an existing PCAP file and output the
packets into a brand new virtual TAP interface (`tap0`).
It simultaneously runs `tcpdump` on the new `tap0` interface to prove
that the kernel is actually receiving the injected packets!

Usage:
    sudo python3 14_tuntap_replay.py
"""

import subprocess, sys, time, os
import pathlib as _pl

_HERE = _pl.Path(__file__).resolve().parent
NETPIPE = str(next(
    (p for p in [
        _HERE / "../../build/bin/netpipe",
        _pl.Path("/usr/local/bin/netpipe"),
        _pl.Path("/usr/bin/netpipe"),
    ] if p.exists()), _HERE / "../../build/bin/netpipe"
))

def main():
    if os.geteuid() != 0:
        print("Please run this script with sudo (TUN/TAP requires root permissions).")
        sys.exit(1)

    # Use the pcap generated by the TLS capture script if it exists
    pcap_path = _HERE / "../../encrypted_traffic.pcap"
    
    if not pcap_path.exists():
        print(f"File not found: {pcap_path}")
        print("Please run `sudo python3 examples/python/10_tls_capture.py wlo1` first to capture some packets!")
        sys.exit(1)

    print(f"\033[1mTAP Replay Demo\033[0m")
    print(f"Replaying \033[36m{pcap_path.name}\033[0m into virtual interface \033[33mtap0\033[0m...\n")

    # 1. Start netpipe playing into tap0 with a rate limit of 10000 bytes/sec
    # so tcpdump has time to catch it before the file ends!
    cmd_netpipe = [NETPIPE, "-r", str(pcap_path), "-o", "tap://tap0", "-rate", "10000", "-q"]
    netpipe_proc = subprocess.Popen(cmd_netpipe)

    # Give it a tiny fraction of a second to initialize the TAP interface
    time.sleep(0.5)
    
    # 2. Make sure the interface is UP so tcpdump can see it
    subprocess.run(["ip", "link", "set", "tap0", "up"], stderr=subprocess.DEVNULL)
    
    # 3. Start tcpdump to capture the replay!
    print("┌── \033[1;35mKernel tcpdump output on tap0\033[0m ─────────────────────")
    
    cmd_tcpdump = ["tcpdump", "-i", "tap0", "-n", "-c", "5"] # Capture just 5 packets to prove it
    try:
        subprocess.run(cmd_tcpdump, check=True)
    except subprocess.CalledProcessError:
        print("\033[1;31mFailed to run tcpdump on tap0.\033[0m")

    print("└────────────────────────────────────────────────────────\n")
    
    # Clean up
    netpipe_proc.terminate()
    netpipe_proc.wait()

if __name__ == "__main__":
    main()
